import SecurityNotation.Logic.Logic
import SecurityNotation.Basic.Syntax.Events
import SecurityNotation.Basic.Syntax.Principal
import SecurityNotation.Basic.Syntax.Keys
import SecurityNotation.Basic.Syntax.Messages
import SecurityNotation.Basic.Syntax.Nonces

def Alice  : Principal := {id := 1, name := "Alice",  role := Role.initiator, known_principals := [2]}
def Server : Principal := {id := 2, name := "Server", role := Role.server,    known_principals := [1]}
def Eve : Principal := {id := 3, name := "Eve", role := Role.adversary, known_principals := [1,2]}

def ServerPublicKey  : Key := Key.new 1 keyType.publicKey  (some Server) [Server] (some 2)
def ServerPrivateKey : Key := Key.new 2 keyType.privateKey (some Server) [Server] (some 1)

def aliceNonce     : Nonce := {randomNum := 100, principal := Alice}
def serverNonce    : Nonce := {randomNum := 200, principal := Server}
def preMasterSecret : Nonce := {randomNum := 300, principal := Alice}  


-- this is needed as in TLS the sessionkey is derived from the nonces give and not generated by a single principal
def deriveSessionKey (pms : Nonce) (cn sn : Nonce) : Key :=
  Key.new 3 keyType.sessionKey none [Alice, Server]

def sessionKey : Key := deriveSessionKey preMasterSecret aliceNonce serverNonce

def test_TLS : Trace := [
  -- Step 1: Alice sends her nonce, adversary forwards it to Server
  Event.send Alice Server (Message.nonce aliceNonce),
  Event.recieve Server (Message.nonce aliceNonce),

  -- Step 2: Server sends nonce + public key, adversary forwards to Alice
  Event.send Server Alice
    (Message.pair (Message.nonce serverNonce) (Message.key ServerPublicKey)),
  Event.recieve Alice
    (Message.pair (Message.nonce serverNonce) (Message.key ServerPublicKey)),

  -- Step 3: Alice sends encrypted premaster secret, adversary forwards to Server
  Event.send Alice Server
    (Message.enc (Message.nonce preMasterSecret) ServerPublicKey),
  Event.recieve Server
    (Message.enc (Message.nonce preMasterSecret) ServerPublicKey),

  -- Step 4: Server sends encrypted confirmation, adversary forwards to Alice
  Event.send Server Alice
    (Message.enc (Message.nonce aliceNonce) sessionKey),
  Event.recieve Alice
    (Message.enc (Message.nonce aliceNonce) sessionKey)
]

/- some proofs i could do:
  - server knows aliceNonce
  - alice knows server public key (can unpack)
  - server can derive premastersecret
  - outsider cannot derive the sessionkey
-/

-- this theorem is pretty self explanatory, it proves that the server knows alice nonce because it was sent it.
theorem serverKnowsAliceNonce :
    Knows Server test_TLS (Message.nonce aliceNonce) := by
      apply Knows.received (s := Alice)
      . decide

-- this theorem is similar to the last one but adds the property that it needs unpacking
-- to solve this we firstly break it down with pair_unpack and then look in trace
theorem aliceKnowsServerPubKey :
    Knows Alice test_TLS (Message.key ServerPublicKey) := by
      apply Knows.pair_unpack_r (m1 := Message.nonce serverNonce)
      apply Knows.received (s := Server)
      . decide

-- this one was a bit harder to solve, we are trying to prove that server knows premastersecret
-- we need to use decrypt and see that server can work out the message sent because it knows the Keys
-- then we need to show it knows its own private key. everything else
-- is just rfl to prove known knowledge.
theorem serverDerivePremastersecret :
    Knows Server test_TLS (Message.nonce preMasterSecret) := by
    apply Knows.decrypt (k_pub := 
    ServerPublicKey) (k_priv := ServerPrivateKey)
    . apply Knows.received (s := Alice)
      . decide
    . apply Knows.knows_own_private_key
      . rfl
      . rfl
    . rfl
    . rfl
    . rfl





section EveCannotDerivePreMasterSecret

--firstly some helper theorems

-- Step 1: Eve has zero trace events, these are used to prove that Eve has not interacted with the trace
private theorem eve_sent_not_in_trace (r : Principal) (m : Message) :
    (Event.send Eve r m) ∉ test_TLS := by
  simp [test_TLS, Eve, Alice, Server]

private theorem eve_received_not_in_trace (m : Message) :
    (Event.recieve Eve m) ∉ test_TLS := by
  simp [test_TLS, Eve, Alice, Server]



-- here we create a new noncefree inductive predicate to prove that Eve never recieves a premastersecret (nonce)
-- this is needed as pair_unppack and decrypt are both recursive as the inside of each are both messages that could possibly
-- contain aother pair that would need to be unpacked or an encoded message that needs decrypting 
-- we use nonce free so that once we look at the message underneath, as long as it falls under nonce free, we can conclude 
-- that putting them together or encrypting them doesnt give us a nonce so it cannot possibly be in there.

inductive NonceFree : Message → Prop where
  | msg   : ∀ s,     NonceFree (Message.message s)
  | agent : ∀ p,     NonceFree (Message.agent p)
  | key   : ∀ k,     NonceFree (Message.key k)
  | pair  : ∀ m1 m2, NonceFree m1 → NonceFree m2 → NonceFree (Message.pair m1 m2)
  | enc   : ∀ m k,   NonceFree m  → NonceFree (Message.enc m k)


-- here we are applying the nonce free predicate to conclude that Eve cannot know the premastersecret
-- given the message and h, we can apply it to either the inductive typing to see that there aren't any nonces
-- in the Nonce free type so she cannot possibly know premaster secret, or we use the helper theorems
-- to prove that they were never in the trace.


theorem eve_knows_nonce_free (m : Message) (h : Knows Eve test_TLS m) : NonceFree m := by
  induction h with
  | knows_agents a _            => exact NonceFree.agent a
  | knows_public_keys k _       => exact NonceFree.key k
  | knows_own_private_key k _ _ => exact NonceFree.key k
  | held_keys k _               => exact NonceFree.key k
  | sent r _ ht                 => exact absurd ht (eve_sent_not_in_trace r _)
  | received s _ ht             => exact absurd ht (eve_received_not_in_trace s _)
  | intercepted _ ht            => exact absurd ht (eve_intercepted_not_in_trace _)
  | pair_pack _ _ _ _ ih1 ih2   => exact NonceFree.pair _ _ ih1 ih2
  | encrypt _ _ _ _ ihm _       => exact NonceFree.enc _ _ ihm
  -- what we do here is take the left half of a pair and use exact to prove it is nonce free
  | pair_unpack_l _ _ _ ih      =>
      cases ih with | pair _ _ h1 _ => exact h1
  -- the same here but with the right half
  | pair_unpack_r _ _ _ ih      =>
      cases ih with | pair _ _ _ h2 => exact h2
  -- this applies the same logic but with encryption, given an enc message, it is only nonce free if the message inside
  -- is nonce free. therefore we encode the message and exact hm to prove it is nonce free. 
  | decrypt _ _ _ _ _ _ _ _ ih_enc _ =>
      cases ih_enc with | enc _ _ hm => exact hm

-- then we have the final proof which states that she doesnt know the premastersecret by applying the previous theorems
theorem EveCannotDerivePremastersecret :
    ¬ Knows Eve test_TLS (Message.nonce preMasterSecret) := by
  intro h
  cases eve_knows_nonce_free _ h

end EveCannotDerivePreMasterSecret
