import SecurityNotation.Logic.Logic
import SecurityNotation.Basic.Syntax.Events
import SecurityNotation.Basic.Syntax.Principal
import SecurityNotation.Basic.Syntax.Keys
import SecurityNotation.Basic.Syntax.Messages
import SecurityNotation.Basic.Syntax.Nonces
import SecurityNotation.Basic.Utils.Notation
import Mathlib

def Alice  : Principal := {id := 1, name := "Alice",  role := Role.initiator, known_principals := [2]}
def Server : Principal := {id := 2, name := "Server", role := Role.server,    known_principals := [1]}
def Eve : Principal := {id := 3, name := "Eve", role := Role.adversary, known_principals := [1,2]}

def ServerPublicKey  : Key := Key.new 1 keyType.publicKey  (some Server) [Server] (some 2)
def ServerPrivateKey : Key := Key.new 2 keyType.privateKey (some Server) [Server] (some 1)

def aliceNonce     : Nonce := {randomNum := 100, principal := Alice}
def serverNonce    : Nonce := {randomNum := 200, principal := Server}
def preMasterSecret : Nonce := {randomNum := 300, principal := Alice}

-- this is needed as in TLS the sessionkey is derived from the nonces and not generated by a single principal
def deriveSessionKey (pms : Nonce) (cn sn : Nonce) : Key :=
  Key.new 3 keyType.sessionKey none [Alice, Server]

def sessionKey : Key := deriveSessionKey preMasterSecret aliceNonce serverNonce

def test_TLS : Trace := [
  -- Step 1: Alice sends her nonce
  Event.send Alice Server (NON aliceNonce),
  Event.recieve Server (NON aliceNonce),

  -- Step 2: Server sends nonce + public key
  Event.send Server Alice
    (⟨ [base (BaseMessage.nonce serverNonce), base (BaseMessage.key ServerPublicKey)] ⟩),
  Event.recieve Alice
    (⟨ [base (BaseMessage.nonce serverNonce), base (BaseMessage.key ServerPublicKey)] ⟩),
  Event.recieve Eve
    (⟨ [base (BaseMessage.nonce serverNonce), base (BaseMessage.key ServerPublicKey)] ⟩),

  -- Step 3: Alice sends encrypted premaster secret
  Event.send Alice Server
    ({| [base (BaseMessage.nonce preMasterSecret)] |} ServerPublicKey),
  Event.recieve Server
    ({| [base (BaseMessage.nonce preMasterSecret)] |} ServerPublicKey),

  -- Step 4: Server sends encrypted confirmation
  Event.send Server Alice
    ({| [base (BaseMessage.nonce aliceNonce)] |} sessionKey),
  Event.recieve Alice
    ({| [base (BaseMessage.nonce aliceNonce)] |} sessionKey)
]

section EveCannotDerivePreMasterSecret

private theorem eve_sent_not_in_trace (r : Principal) (m : MessageEnc2) :
    (Event.send Eve r m) ∉ test_TLS := by
  simp [test_TLS, Eve, Alice, Server]

private theorem eve_received_not_in_trace (s : Principal) (m : MessageEnc2) :
    (Event.send s Eve m) ∉ test_TLS := by
  simp [test_TLS, Eve, Alice, Server]

private theorem eve_knowsFromTrace (m : MessageEnc2) (h : KnowsFromTrace Eve test_TLS m ) :
      m = (⟨ [base (BaseMessage.nonce serverNonce), base (BaseMessage.key ServerPublicKey)] ⟩) ∨
      m = (NON aliceNonce) ∨
      m = ({|[base (BaseMessage.nonce preMasterSecret)]|}ServerPublicKey) ∨
      m = {|[base (BaseMessage.nonce aliceNonce)]|}sessionKey := by
  cases h with
  | sent r m h1 =>
    simp [test_TLS, Eve, Alice, Server] at h1
  | received s m h1 =>
    simp [test_TLS, Eve, Alice, Server] at h1
  | intercepted m h1 =>
    simp [test_TLS, Eve, Alice, Server] at h1
    subst h1
    simp
  | adversary_observes s r m h1 h2 =>
    simp [test_TLS, Eve, Alice, Server] at h2
    rcases h2 with h2 | h2 | h2 | h2
    all_goals
    · have h' := h2.2.2
      subst h'
      simp





theorem eve_not_knowFromTrace_preMasterSecret :
    ¬ KnowsFromTrace Eve test_TLS (NON preMasterSecret) := by
  intro h
  have h1 := eve_knowsFromTrace (NON preMasterSecret) h
  simp [aliceNonce, preMasterSecret] at h1

theorem EveCannotDerivePremastersecret :
    ¬ Knows Eve test_TLS (NON preMasterSecret) := by
  intro h
  have hl := eve_not_knowFromTrace_preMasterSecret
  cases h with
  | from_trace m h1 => simp_all
  | decrypt => sorry
  | decrypt_fst => sorry
  | tuple_unpack_of_trace ms h1 h2 h =>
    have h3 := eve_knowsFromTrace (⟨ ms ⟩) h2
    simp at h3
    subst h3
    simp at h
    sorry







end EveCannotDerivePreMasterSecret
